In [1]:
#google.colab, #pip install numpy
import numpy as np

In [5]:
a = np.array([0,1,2,3,4,5,6,7])
print(a)

[0 1 2 3 4 5 6 7]


In [3]:
a.ndim

1

In [6]:
a.shape

(8,)

In [7]:
b = a.reshape((2,4))
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [8]:
b.ndim

2

In [9]:
b.shape

(2, 4)

In [11]:
c = np.arange(24).reshape((4,6))
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
print(c[2, 3])

15


In [13]:
c[2,3]=69
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 69 16 17]
 [18 19 20 21 22 23]]


In [14]:
c[0,0] =420
print(c)

[[420   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  69  16  17]
 [ 18  19  20  21  22  23]]


In [16]:
print(c[0])

[420   1   2   3   4   5]


In [17]:
#print everything in the last column

In [20]:
print(c[:,-2])

[ 4 10 16 22]


In [21]:
print(c[1:])

[[ 6  7  8  9 10 11]
 [12 13 14 69 16 17]
 [18 19 20 21 22 23]]


In [22]:
print(c[:2])

[[420   1   2   3   4   5]
 [  6   7   8   9  10  11]]


In [23]:
d = np.arange(24).reshape(2,3,4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [24]:
#how would you get to number 18,
print(d[1, 1, 2])

18


In [25]:
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [26]:
b.dtype

dtype('int64')

In [27]:
e = np.array([1,2,3,4,5,6], dtype='int16')
print(e)

[1 2 3 4 5 6]


In [28]:
e.dtype

dtype('int16')

In [29]:
e.astype('int32')

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [31]:
f = e.reshape((2,3))
print(f)

[[1 2 3]
 [4 5 6]]


In [32]:
g = f + 10
print(g)

[[11 12 13]
 [14 15 16]]


In [33]:
h = g * 3
print(h)

[[33 36 39]
 [42 45 48]]


In [ ]:
#matrix multiplication, (2,3) matmul (3,4) , answer will have a (2,4)

In [34]:
i = np.arange(12).reshape((3,4))
print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
after_mat_multiplication = np.matmul(h,i)
print(after_mat_multiplication)

[[456 564 672 780]
 [564 699 834 969]]


In [38]:
test0 = np.zeros((2,4), dtype='int32')
print(test0)

[[0 0 0 0]
 [0 0 0 0]]


In [39]:
test0.dtype

dtype('int32')

In [40]:
test1 = np.ones((2,4), dtype='int32')
print(test1)

[[1 1 1 1]
 [1 1 1 1]]


In [42]:
combined_array = np.append(test0, test1, axis=0)
print(combined_array)

[[0 0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1 1]]


In [43]:
fake_arrays = np.full((2,3,5), 69)
print(fake_arrays)

[[[69 69 69 69 69]
  [69 69 69 69 69]
  [69 69 69 69 69]]

 [[69 69 69 69 69]
  [69 69 69 69 69]
  [69 69 69 69 69]]]
